apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: slack-mcp-agent
  app.kubernetes.io/component: agent
  app.kubernetes.io/part-of: vops

images:
  - name: us-east1-docker.pkg.dev/unity-vivox-docker-registry/mcp-vivox-ops/slack-mcp-agent
    newTag: latest
